[package]
name = "pack2"
version = "0.1.0"
authors = ["Michael Sprecher <dev@0x23.ch>"]
edition = "2018"

[dependencies]
bstr = "0.2.12"
hashbrown = "0.7.2"
faster-hex = { git = "https://github.com/ggriffiniii/faster-hex", branch = "master" }
structopt = "0.3"
